### ISSUE TITLE
Ye Olde Tanks crashing client

### ISSUE THREAD

**Issue by Oeniarku** [Forecaster/RailcraftPatronServerIssues#37]
Crafted barrel from YeOldeTanks. Immediately after placing it, my client crashed. Now, when i'm trying to connect - same error. At least i know my coordinates now. 
```
Caused by: java.lang.IllegalArgumentException: No TileEntity at position BlockPos{x=-2466, y=118, z=-2447}
	at net.shadowfacts.shadowmc.block.TileEntityProvider.getTileEntity(TileEntityProvider.java:32)
	at net.shadowfacts.yeoldetanks.block.base.BlockBarrelBase.getLightValue(BlockBarrelBase.java:147)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightValue(BlockStateContainer.java:481)
	at net.minecraft.block.Block.func_185484_c(Block.java:382)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185889_a(BlockStateContainer.java:349)
	at team.chisel.client.ChiselExtendedState.func_185889_a(ChiselExtendedState.java:41)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.updateLightmap(VertexLighterFlat.java:244)
	at net.minecraftforge.client.model.pipeline.VertexLighterFlat.processQuad(VertexLighterFlat.java:165)
	at net.minecraftforge.client.model.pipeline.QuadGatheringTransformer.put(QuadGatheringTransformer.java:63)
	at net.minecraftforge.client.model.pipeline.LightUtil.putBakedQuad(LightUtil.java:133)
	at net.minecraft.client.renderer.block.model.BakedQuad.pipe(BakedQuad.java:66)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:124)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187497_c(ForgeBlockModelRenderer.java:82)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:46)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:37)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	... 16 more

```
[like this](https://github.com/shadowfacts/YeOldeTanks/issues/27)

**Comment by Oeniarku** [comment]
Nevermind. It appears only if you turn off Smooth Lighting. I was playing on a laptop. And now on my pc every thing is fine. But if i turn off Smooth Lighting - it crashes same as on a laptop. I tested it on clean 1.10.2, forge 12.18.3.2281 and YeOldeTanks-1.10.2-2.0.1 + ShadowMC-1.10.2-3.6.1. Identical error.

**Comment by Forecaster** [comment]
You should report that to the mod

**Comment by Oeniarku** [comment]
YeOldeTanks 2.0.2 fixed
